apiVersion: v1
kind: Service
metadata:
  name: openvpn
  namespace: {{ .Values.namespace }}
  labels:
    app: openvpn
spec:
  type: LoadBalancer
  ports:
    - name: openvpn
      port: 1194
      targetPort: 1194
      protocol: UDP
  selector:
    app: openvpn
